name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Add GitHub Packages source
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/andrei-shershan/index.json \
          --name github \
          --username andrei-shershan \
          --password ${{ secrets.READ_PACKAGE_KEY }} \
          --store-password-in-clear-text

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal